In [ ]:
import os

In [ ]:
a = '/Users/congthanhnguyen/hachi-x/product/Horita/HoritaStationery/Server/report//prediction_result.json'

In [9]:
print(a)

[ 1.87015994  1.85916331 -0.17298711 -0.38167522  0.83036175]


In [23]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [24]:
print(c)

[[ 1.62153126 -1.16096255 -0.26280543]
 [-0.04256082 -0.20459165 -0.28911992]
 [ 0.05810037 -3.64045805  2.22899688]]


In [25]:
print(a)

[[-1.53831767  1.10138438  0.2493188 ]
 [ 0.23741099  1.1412447   1.61275682]
 [-0.02049414  1.2841239  -0.78624946]]


In [26]:
print(b)

[[-1.0540939 ]
 [-0.17927062]
 [-2.83497413]]


In [29]:
print(1.10138438*1.0540939)

1.1609625565132822


In [16]:
print(np.dot(a, a.T))

[[ 0.20689627 -0.13791614  0.20462663  0.50246485 -0.29282398]
 [-0.13791614  0.0919343  -0.13640322 -0.33494086  0.19519518]
 [ 0.20462663 -0.13640322  0.2023819   0.49695285 -0.28961172]
 [ 0.50246485 -0.33494086  0.49695285  1.22027779 -0.71114745]
 [-0.29282398  0.19519518 -0.28961172 -0.71114745  0.41443899]]


In [17]:
print(np.dot(a.T, a))

[[2.13592925]]


In [13]:
print(d)

2019-01-26 15:52:59.556824


In [14]:
ts = 1548484831164

In [18]:
e = datetime.datetime.Date(ts)

AttributeError: type object 'datetime.datetime' has no attribute 'Date'

In [19]:
import time

In [20]:
f = time.ctime(ts)

In [21]:
print(type(f))

<class 'str'>


In [22]:
print(f)

Sun Jul 14 12:19:24 51039


In [24]:
abc = '2019/1/26'
format_date = '%Y/%m/%d'
data_start_datetime_obj = datetime.datetime.strptime(abc, format_date)

In [25]:
print(type(data_start_datetime_obj))

<class 'datetime.datetime'>


In [6]:
import datetime
import time

In [2]:
now = datetime.datetime.now()

In [3]:
print(type(now))

<class 'datetime.datetime'>


In [8]:
today = now.date()
b = datetime.datetime.combine(today, datetime.datetime.min.time())

In [10]:
print(type(b))

<class 'datetime.datetime'>


In [11]:
print(b)

2019-04-05 00:00:00
